### PR TITLE
Create en.po

### PR DESCRIPTION
**Pull request by ghost**
Dear developer!
Please maintain an English po file if possible.
I think others can use your development as long as they respect the license.

is this possible?

Thank you very much!

Regards,
The Lacesz

### CODE REVIEW

**Comment by Niklan** [comment]
Hi, can you explain why is that necessary? Those English strings will be imported from the code via usage of `t()` and `new TranslatableMarkup`. You don't need to import English translations because English can't be translated to English in Drupal.

Maybe I'm missing something, but I think this is not necessary in the context of Drupal.

**Comment by Niklan** [comment]
For reference: https://localize.drupal.org/translate/drupal_core - you can't download en.po and translate English even on localize website because English (US) is default language for Drupal and all those strings are in code, except .po (translation) files.

**Comment by andypost** [comment]
You can export all strings with dgo.to/potx

No reason to ship en.po file (as it used in D5/6/7

**Comment by Niklan** [comment]
Thank you for feedback. You are welcome to reopen or reply here, I closing it because this file doesn't make sense to me. Also we got another opinion that it's not necessary.

**Comment by ghost** [comment]
Thank you very much!

so I understand what you are telling me.

**Pull request closed without merging**
